### ISSUE TITLE
Add FreeBSD support

### ISSUE THREAD

**Issue by trtrmitya** [crs4/pydoop#102]
I made a simple patch to support FreeBSD OS in system checks in jvm.py.

http://people.freebsd.org/~demon/patch-pydoop-utils-jvm.py

**Comment by mdrio** [comment]
Hi, thanks for the patch! 
The best way to add external contributions should be a pull request, do you mind to make one?

**Comment by trtrmitya** [comment]
I don't use git, sorry.

**Comment by mdrio** [comment]
ok, I'll do a pull request with your patch.

**Comment by elzaggo** [comment]
Merged in develop from pull request #103.
