### ISSUE TITLE
support of Hadoop 2.2.0 from HDP-2.0.6

### ISSUE THREAD

**Issue by mdespriee** [crs4/pydoop#11]
Trying to install pydoop, I get the following error :
RuntimeError: none of the supported versions is close enough to 2.2.0.2.0.6.0-76

Is it a bug from the installer, or is it this precise version that is not supported ?
The hadoop cluster is a fresh install of a HDP 2.0.6

Any idea when this version will be supported ?
Thanks for you answer !

**Comment by elzaggo** [comment]
Support to hdp (tested on hdp22) added with #121.
