### ISSUE TITLE
Support for overwriting existing files/directories with hdfs.cp()?

### ISSUE THREAD

**Issue by fibbo** [crs4/pydoop#110]
If I want to copy a folder with hdfs.cp(src, dest) to a HDFS storage and this folder already exists it just raises an IOError and that's it. Is it planned to allow overwriting files/directories?

**Comment by ilveroluca** [comment]
Hi there,

no, I don't think changing the behaviour of the existing function would be a good idea.  The API does provide the necessary functionality to write such a function in client code though.

**Comment by fibbo** [comment]
Alright, I see. Thanks for the reply!
