### ISSUE TITLE
Can't install pydoop on OSX 10.10

### ISSUE THREAD

**Issue by alicealbrecht** [crs4/pydoop#129]
Hello,

     I'm fairly new to hadoop and am trying to use your software for a tutorial on hortonworks.  I have been trying to install your package for days and I simply can't figure it out.  I tried pip install pydoop and I get the following error.  I can't find how to set HADOOP_VERSION.  When I type hadoop version into the terminal I get the following:  

hadoop version:
Hadoop 2.6.0
Subversion https://git-wip-us.apache.org/repos/asf/hadoop.git -r e3496499ecb8d220fba99dc5ed4c99c8f9e33bb1
Compiled by jenkins on 2014-11-13T21:10Z
Compiled with protoc 2.5.0
From source with checksum 18e43357c8f927c0695f1e9522859d6a
This command was run using /usr/local/Cellar/hadoop/2.6.0/libexec/share/hadoop/common/hadoop-common-2.6.0.jar

pip install pydoop error:
Downloading/unpacking pydoop
Exception:
Traceback (most recent call last):
  File "/Users/alicealbrecht/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/Users/alicealbrecht/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/alicealbrecht/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pip/req.py", line 948, in prepare_files
    location = req_to_install.build_location(self.build_dir, not self.is_download)
  File "/Users/alicealbrecht/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pip/req.py", line 150, in build_location
    _make_build_dir(build_dir)
  File "/Users/alicealbrecht/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pip/req.py", line 1192, in _make_build_dir
    os.makedirs(build_dir)
  File "/Applications/Canopy.app/appdata/canopy-1.4.0.1938.macosx-x86_64/Canopy.app/Contents/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/build'

Storing complete log in /Users/alicealbrecht/.pip/pip.log

**Comment by kikkomep** [comment]
Hi! 
Are HADOOP_HOME and HADOOP_CONF_DIR in your environment?

If you are using homebrew hadoop:
```
HADOOP_HOME=/usr/local/Cellar/hadoop/2.6.0/libexec/
HADOOP_CONF_DIR=/usr/local/Cellar/hadoop/2.6.0/libexec/etc/hadoop
```

**Comment by alicealbrecht** [comment]
I installed hadoop but I don't think I used homebrew.  I tried the two commands you recommended and the first one seemed to work but the second threw an error saying that:
-sh: HADOOP_CONF_DIR: command not found

I tried pip install pydoop again and got the same error message 

 ValueError: hadoop version not found, try setting HADOOP_VERSION
    Complete output from command python setup.py egg_info:
    using setuptools version 15.1

I tried HADOOP_VERSION = 2.6.0- which seemed to work but then the pip install pydoop failed again.

**Comment by kikkomep** [comment]
How did you installed Hadoop? Which version of Python are you using?

**Comment by simleo** [comment]
@alicealbrecht those are settings, not commands. What you have to type on the shell is:

    export HADOOP_HOME=/usr/local/Cellar/hadoop/2.6.0/libexec
    export HADOOP_CONF_DIR=/usr/local/Cellar/hadoop/2.6.0/libexec/etc/hadoop

**Comment by alicealbrecht** [comment]
@ simleo I tried using export- that didn't solve the issue

I used this website as a reference for installing Hadoop http://amodernstory.com/2014/09/23/installing-hadoop-on-mac-osx-yosemite/.  

My hadoop version is:
Hadoop 2.6.0
Subversion https://git-wip-us.apache.org/repos/asf/hadoop.git -r e3496499ecb8d220fba99dc5ed4c99c8f9e33bb1
Compiled by jenkins on 2014-11-13T21:10Z
Compiled with protoc 2.5.0
From source with checksum 18e43357c8f927c0695f1e9522859d6a
This command was run using /usr/local/Cellar/hadoop/2.6.0/libexec/share/hadoop/common/hadoop-common-2.6.0.jar

and my python version is:
Enthought Canopy Python 2.7.6 | 64-bit | (default, Apr 11 2014, 11:55:30) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by kikkomep** [comment]
You are actually using Homebrew Hadoop, but not Homebrew Python: I suggest that you install it. 
As a first step, type:
```
brew update && brew doctor
```
... to update your homebrew packages and check whether your Homebrew installation is ok (every possibile issue is shown as warning by the output of the above command: e.g., missing XCode, etc.).

The next step is to install Homebrew Python:
```
brew install python 
```
and check you are using the Homebrew version of Python typing:
```
python --version
```
(expected output: ```Python 2.7.9```).

Set HADOOP_HOME and HADOOP_CONF_DIR:
```
export HADOOP_HOME=/usr/local/Cellar/hadoop/2.6.0/libexec/
export HADOOP_CONF_DIR=/usr/local/Cellar/hadoop/2.6.0/libexec/etc/hadoop/
```
and finally try to install Pydoop using pip:
```
pip install pydoop
```

**Comment by alicealbrecht** [comment]
Thanks @kikkomep.  I had some outstanding issues when I ran brew doctor and had some warnings but tried to solve most of them.  I then ran brew install python and here is the end of the output.  It looks like my python version is still 2.7.6 and when I run pip install pydoop is still has the same error:

Run `brew linkapps python` to symlink these to /Applications.
==> /usr/local/Cellar/python/2.7.9/bin/python -s setup.py --no-user-cfg install --force --verbose --install-script
==> /usr/local/Cellar/python/2.7.9/bin/python -s setup.py --no-user-cfg install --force --verbose --install-script
==> Summary
🍺  /usr/local/Cellar/python/2.7.9: 4808 files, 77M
monthnext-lm:~ alicealbrecht$ python --version
Python 2.7.6 --  64-bit

**Comment by alicealbrecht** [comment]
Actually- now I'm getting a JAVA_HOME issue.  
RuntimeError: java home not found, try setting JAVA_HOME

**Comment by alicealbrecht** [comment]
And my java directory is not what is expected on the website's tutorial instructions: 

/usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home

**Comment by alicealbrecht** [comment]
I think I've got it fixed- Thanks!

**Comment by swapnilsoni** [comment]
For mac users: in .bash_profile
HADOOP_HOME=<HOME PATH>
HADOOP_VERSION=<VERSION>
export HADOOP_HOME
export HADOOP_VERSION
