### ISSUE TITLE
Pydoop Install with cloudera Hadoop CDH5 - Version Incompatibility

### ISSUE THREAD

**Issue by SANDEEPGUPTAU** [crs4/pydoop#14]
[root@snb3-top pydoop-0.11.1]# python setup.py build running build 
>> running build_py running build_ext Traceback (most recent call last):
>>     File "setup.py", line 592, in <module>
>>       ('config', ['README.md']),
>>     File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
>>       dist.run_commands()
>>     File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
>>       self.run_command(cmd)
>>     File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
>>       cmd_obj.run()
>>     File "/usr/lib64/python2.6/distutils/command/build.py", line 134, in run
>>       self.run_command(cmd_name)
>>     File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
>>       self.distribution.run_command(command)
>>     File "/usr/lib64/python2.6/distutils/dist.py", line 994, in run_command
>>       cmd_obj.ensure_finalized()
>>     File "/usr/lib64/python2.6/distutils/cmd.py", line 117, in ensure_finalized
>>       self.finalize_options()
>>     File "setup.py", line 466, in finalize_options
>>       self.EXT_MANAGER.patch_src()
>>     File "setup.py", line 423, in patch_src
>>       self.patched_src_dir = self.patcher.patch()
>>     File "setup.py", line 284, in patch
>>       closest_tag = self.__link_closest_tag()
>>     File "setup.py", line 212, in __link_closest_tag
>>       self.hadoop_version_info
>> RuntimeError: none of the supported versions is close enough to
>> 2.3.0-cdh5.0.0

**Comment by simleo** [comment]
Hi all,

the new version is finally out, with support for CDH5. Since it's a release candidate, if you are installing with pip, remember to include the `--pre` flag.

Thanks for your patience!
