### ISSUE TITLE
CombineRunner does not make defensive copies of emitted values

### ISSUE THREAD

**Issue by simleo** [crs4/pydoop#141]
In the current implementation of `CombineRunner`, unexpected behavior can arise, when running in private_encoding mode, if the Mapper modifies an object after emitting it. This is due to the fact that we are not making defensive copies of emitted values.

This is a potential source of bugs for applications that use combiners with private_encoding enabled. The immediate workaround is to make sure that that the Mapper does **not** modify any value that's already been emitted.

**Comment by simleo** [comment]
Since making copies unconditionally is quite expensive, we could do something like this:

    from copy import deepcopy
    try:
        hash(value)
    except TypeError:
        value = deepcopy(value)
    self.data.setdefault(key, []).append(value)

**Comment by elzaggo** [comment]
Probably fixed by PR #142
