### ISSUE TITLE
Known issues: from-tarball CDH installation is not supported.

### ISSUE THREAD

**Issue by justinuang** [crs4/pydoop#146]
Hi,

I'm trying to use pydoop in order to get a file-like object for use in my python libraries. Would it be really complicated to get support for from-tarball CDH installations?

On a side note, if the code changes required would be too complicated, are there other libraries that give me a file-like object to access whatever Hadoop FileSystem I have? (S3, local, hdfs)

Thanks in advance!

**Comment by elzaggo** [comment]
Hi Justin,

I believe that, technically, you should be able to install pydoop 1.0 with minimal informations on the installed Hadoop. What kind of difficulties are you experiencing? 

--gianluigi

**Comment by elzaggo** [comment]
We consider the issue closed. At least for the time being.
