### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by MariusDieck** [crs4/pydoop#156]
Hi,

i tried to make use of hadoop for a project of mine, however when i run the all_tests.py script it displays a segmentation fault without any further information. I use hadoop v2.6.0 and i tried to install pydoop via pip and via source but both gave me the same error. However to install it i used sudo -E pip install pydoop rather than pip install pydoop. The test that fails is: test_generate_code_no_env_override (test_submit.TestAppSubmit) ... Speicherzugriffsfehler [<- segmentation fault]

The cluster is a single node cluster (only want to show for my BA thesis that using pydoop is faster with avro than using normal streaming).
Besides pydoop the cluster runs fine.

Greets

**Comment by mdrio** [comment]
Hi, on which OS are you running? You tried local and system installation but in both cases test_generate_code_no_env_override  exited with as segmentation fault, right?

**Comment by MariusDieck** [comment]
Its a Linux Mint 17.2 (based on Ubuntu 14.04 LTS) with Kernel 3.16.0-38. Yes i tried after building sudo -E python setup.py install --skip-build 
and 
sudo -E python setup.py install --skip-build --user

both caused the same testing error

**Comment by mdrio** [comment]
I assume you run python setup.py build before, didn't you?

**Comment by MariusDieck** [comment]
Yes i have ;)

**Comment by mdrio** [comment]
```
sudo -E python setup.py install --skip-build --user
```
I think the final arg `--user` can be confusing, since you are using sudo.

**Comment by MariusDieck** [comment]
I tried
sudo -E python setup.py install --skip-build
and
python setup.py install --skip-build --user

from the pydoop dir but it did not work... do i need to delete the old files maybe?
Btw. the version without sudo does not work due to writing restrictions

**Comment by mdrio** [comment]
can you paste the exceptions?

**Comment by MariusDieck** [comment]
the one that occurs when i try to run pydoop or when i try to install it without sudo?

**Comment by mdrio** [comment]
let's see `python setup.py install --skip-build --user` first

**Comment by MariusDieck** [comment]
using setuptools version 3.3
running install
running bdist_egg
running egg_info
writing requirements to pydoop.egg-info/requires.txt
error: [Errno 13] Permission denied: 'pydoop.egg-info/requires.txt'

**Comment by mdrio** [comment]
let's do from the beginning:
```
git clean -xfd
python setup.py build
python setup.py install --skip-build --user
```

**Comment by MariusDieck** [comment]
executed this in the cloned git dir, still the same error

**Comment by mdrio** [comment]
mmm it seems you cannot write in the cloned dir... Maybe it is better to clone the repo in another dir...
Try

```
git clone https://github.com/crs4/pydoop.git /tmp/pydoop
cd /tmp/pydoop
python setup.py build
python setup.py install --skip-build --user

``

**Comment by MariusDieck** [comment]
This returns this (the last part):
http://pastebin.com/JeWjWNvw
I guess i have to delete old files in home/marius/.local/lib/python2.7/site-packages

**Comment by mdrio** [comment]
Yes,  I also suggest you to delete the files of the system level
installation, if they exist.

Il giorno mar 21 lug 2015 19:32 MariusDieck <notifications@github.com> ha
scritto:

**Comment by MariusDieck** [comment]
Okay now i get this error:
[Errno 13] Permission denied: '/home/marius/.local/bin/pydoop'

**Comment by mdrio** [comment]
Remove that file and try to install again

Il giorno mar 21 lug 2015 21:01 MariusDieck <notifications@github.com> ha
scritto:

**Comment by MariusDieck** [comment]
Already tried that... does not work

**Comment by mdrio** [comment]
Did you remove it with sudo?

Il giorno mar 21 lug 2015 21:03 MariusDieck <notifications@github.com> ha
scritto:

**Comment by MariusDieck** [comment]
sudo rm -r *path*, it was a dir but this should not change anything i guess...

**Comment by elzaggo** [comment]
Hi!
Have you resolved your installation problem?

--gianluigi

**Comment by MariusDieck** [comment]
Well kind of... i installed a new OS... then it worked... so i guess my OS had a problem, however i only saw that problem with pydoop... i have no idea what happened but thanks anyways xD

**Comment by skeptric** [comment]
Hi; I am getting a very similar problem to the original post.

I first tried installing with "pip install pydoop" inside a virtualenv; but whenver I try to submit a job (pydoop script; pydoop submit) I get a segmentation fault.
I then tried installing from source, master branch (release 1.2.0), inside a virtualenv with the same results.
I then tried a local user installation from source (no virtualenv), with the same results.
I have not tried a system wide installation; I can request this if it may resolve the situation.

In all cases when I try to run all_tests.py I get:
`test_generate_code_no_env_override (test_submit.TestAppSubmit) ... Segmentation fault`

It appears to be Segfaulting on the line:
`self.submitter.set_args(args)`

I am running with:
* Ubuntu 12.0.4 LTS
* Python 2.7.3
* Java 1.6.0_35 (Open JDK 64 bit)
* CDH-4.3.1-1

Thanks

**Comment by skeptric** [comment]
It seems like the issue may be I haven't correctly configured environment variables

By setting HADOOP_CONF_DIR (in my case to /etc/hadoop) I get past that line and get a segfault later (test_local_fs.TestConnection).
I need to check how to correctly configure configure HDFS_HOST and HDFS_PORT and HADOOP_HOME.

**Comment by skeptric** [comment]
When I try to submit a job with HADOOP_CONF_DIR set as it is I get an error
`ERROR - LocalModeNotSupported:  ERROR: Hadoop is configured to run in local mode`

All my actual configuration files are in '/etc/hadoop/conf'; looking at pydoop/hadoop_utils.py it looks like that should be my HADOOP_CONF_DIR. However setting it to that leads to a segfault.

**Comment by skeptric** [comment]
It seems that the configuration of environment variable was a red herring; Pydoop does a good job of detecting those itself.

I have somehow got it to work; but I'm not sure how.
I installed JPype and I tried changing the compiler flags

`CFLAGS='-Wall -O0' python setup.py build --user`

Unfortuanely I can't get it repeatable so I can't work out what actually sovled the problem. I'll update if I do.
