### ISSUE TITLE
pydoop install errors via pip install

### ISSUE THREAD

**Issue by sd2302** [crs4/pydoop#161]
Hi Team,

Can you please help me on this?

pip install pydoop gives error below for HDP 2.3 

export JAVA_HOME = /usr/lib/jvm/java-1.7.0-openjdk.x86_64
export HADOOP_CONF_DIR=/etc/hadoop/conf
export HADOOP_HOME=/usr/hdp/2.3.0.0-2130/hadoop

    running build_scripts
    creating build/scripts-2.6
    copying and adjusting scripts/pydoop -> build/scripts-2.6
    changing mode of build/scripts-2.6/pydoop from 644 to 755
    hadoop_home: '/usr/hdp/2.3.0.0-2130/hadoop'
    hadoop_version: '2.7.1.2.3.0.0-2130'
    java_home: '/usr/lib/jvm/java-1.7.0-openjdk.x86_64'
    Building java code for hadoop-2.7.1.2.3.0.0-2130
    Compiling Java classes
    src/v2/it/crs4/pydoop/NoSeparatorTextOutputFormat.java:25: error: package org.apache.hadoop.fs does not exist
    import org.apache.hadoop.fs.FileSystem;
                               ^
    src/v2/it/crs4/pydoop/NoSeparatorTextOutputFormat.java:26: error: package org.apache.hadoop.fs does not exist
    import org.apache.hadoop.fs.FSDataOutputStream;
                               ^

**Comment by elzaggo** [comment]
See #158.
