### ISSUE TITLE
CDH5 no reducer job no output data

### ISSUE THREAD

**Issue by mkzkv** [crs4/pydoop#166]
Hello, 
we have build some framework on pydoop. After migration to CDH5, jobs with no reduce phase does not write any data on output. Did U met with this before?

```
#  uname -a
Linux hadice.dev 2.6.32-openvz #1 SMP Mon Apr 7 09:46:10 CEST 2014 x86_64 GNU/Linux
# cat /etc/debian_version 
7.9
# dpkg -l | grep hadoop
....
ii  hadoop                               2.6.0+cdh5.4.5+626-1.cdh5.4.5.p0.8~wheezy-cdh5.4.5 all          A software platform for processing vast amounts of data
ii  hadoop-0.20-mapreduce                2.6.0+cdh5.4.5+626-1.cdh5.4.5.p0.8~wheezy-cdh5.4.5 amd64        A software platform for processing
.....
```

Thanks.
Martin Kouril

**Comment by ilveroluca** [comment]
Hi Martin,

I haven't tried with CDH5, but I've run map-only jobs on other Hadoop distributions with any problems.  Have you tried with any other version of Hadoop?

**Comment by mkzkv** [comment]
Hi,
yes we had no problem on CDH4+squeeze. After migration, this happened. Everything else is working fine. So I made some dummy copy reducer as fast hox fix. I'm just asking if You tried to run pydoop job od CDH5 without reduce phase. Probably problem is on our side. 
Thanks for out time.

**Comment by elzaggo** [comment]
Hi Martin,
in the travis tests we check CDH5 and there are map-only examples, e.g., pydoop/examples/pydoop_script/caseswitch.py. 

--gianluigi
