### ISSUE TITLE
Pydoop fails to run wordcount example

### ISSUE THREAD

**Issue by alexiworld** [crs4/pydoop#169]
Running wordcount example fails due to timeout, most probably caused by "WARN mapreduce.JobResourceUploader: No job jar file set.  User classes may not be found. See Job or Job#setJar(String)." issue.

The wordcount example is taken from http://crs4.github.io/pydoop/tutorial/pydoop_script.html and the executing command is:
pydoop script -c combiner wordcount.py /playground/wordcount.dat /playground/wordcount.out

The hadoop is created using the docker container from https://github.com/sequenceiq/hadoop-docker

Please note there are no problems with standard running of python map and reduce described in http://cs.smith.edu/dftwiki/index.php/Hadoop_Tutorial_2_--_Running_WordCount_in_Python article.

**Comment by kikkomep** [comment]
Hi! 

Probably you have some issues with your Hadoop configuration. 
You can try to run the pydoop script using our dockerized Hadoop available on DockerHub (image name: ```crs4/hadoop-apache-2.7.1```).

Use the following commands to pull and run the Docker image:

1. ```docker pull crs4/hadoop-apache-2.7.1```
2. ```docker run -it --rm -p 8088:8088 -p 50070:50070 -p 8042:8042 -p 19888:19888 -h docker-hadoop  crs4/hadoop-apache-2.7.1```

Note that Hadoop is installed on ```/opt/hadoop```and all Hadoop utility commands are setted in the ```PATH``` of the running container. 

To install ```pydoop```use can launch the ```install-pydoop``` script within the running Docker container.

Finally, load your input file into the HDFS and try to run the Pydoop script example.
