### ISSUE TITLE
Write confirmation

### ISSUE THREAD

**Issue by vkuznet** [crs4/pydoop#173]
Hi, I'm new to hadoop/pydoop and working on a system which should ensure that data is safely written to HDFS. I'm using pydoop APIs, in particular dump API, but I can't find anywhere in documentation how to confirm that my write operation is succeeded. The way I check now I store data and read it back, which I'm not sure if it is the most efficient way to that. Can anyone help me to clarify this question?
Thanks,
Valentin.

**Comment by ilveroluca** [comment]
The Pydoop API should raise an IOError if an error is detected by HDFS.  Verify whether the guarantees offered by the HDFS `write` call are sufficient for your application.  Oh, you may also find useful the file checksums provided directly by HDFS.

**Comment by vkuznet** [comment]
Ok, thanks, that would be sufficient.
