### ISSUE TITLE
Passing job configuration parameters to map reduce jobs

### ISSUE THREAD

**Issue by stiegerb** [crs4/pydoop#183]
Hi,

I'm trying to find a way to use the JobConf class with context.get_job_conf(), so pass custom parameters to my custom RecordReader, Mapper, and Reducer classes. For example, I'd like to give the location of an avro schema file to my reader class.

I found the description of the JobConf API, which seems to be what I'm looking for:
http://crs4.github.io/pydoop/api_docs/mr_api.html#pydoop.mapreduce.api.JobConf

And I know that mapreduce.pipes.run_task takes a custom TaskContext class as an optional argument, but I'm not able to find out how to pass the configuration to the context, such that it is available in the RecordReader/Mapper/Reducer classes at run time.

Am I missing part of the documentation, or is there an example somewhere how to use the job config?

Thanks,
Benjamin

**Comment by elzaggo** [comment]
Hi.
Did you try adding  -Dmykeys.keyname=VALUE flags to add configuration parameters? 
The basic documentation is http://crs4.github.io/pydoop/running_pydoop_applications.html  and, as an example, you can look here https://github.com/crs4/pydoop/blob/develop/examples/avro/py/run_avro_parquet_in_out.sh

Let me know if this solves your problem.

--gianluigi

**Comment by stiegerb** [comment]
Hi Gianluigi,
Thanks for the feedback. Do I understand correctly that adding `-D keyname=VALUE` will make `context.get_job_conf.get(keyname)` return `VALUE`?

I guess the actual example code would be this:
https://github.com/crs4/pydoop/blob/develop/pydoop/avrolib.py#L112-L142

I'll try it out and close the issue if it solves my problem.

Thanks,
Benjamin

**Comment by stiegerb** [comment]
Works! Thanks again for the quick turnaround.
