### ISSUE TITLE
【RuntimeError】 module not initialized, check that Pydoop is correctly installed

### ISSUE THREAD

**Issue by xyniceboy** [crs4/pydoop#189]
import pydoop.hdfs as hdfs
hdfs.mkdir("test")
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "pydoop/hdfs/__init__.py", line 262, in mkdir
      fs = hdfs(host, port, user)
    File "pydoop/hdfs/fs.py", line 150, in __init__
      h, p, u, fs = _get_connection_info(host, port, user)
    File "pydoop/hdfs/fs.py", line 64, in _get_connection_info
      fs = core_hdfs_fs(host, port, user)
    File "pydoop/hdfs/core/__init__.py", line 55, in core_hdfs_fs
      'module not initialized, check that Pydoop is correctly installed'
    RuntimeError: module not initialized, check that Pydoop is correctly installed
 
I have change the 2 items, but no useful. Have you ever encountered the problem ? 
1. /usr/local/lib/python2.7/site-packages/pydoop/hadoop_utils.py
def init(self):
#self.__hadoop_home = None
self.__hadoop_home = /home/hdfs/hdfs
self.__hadoop_conf = /home/hdfs/hdfs/etc/hadoop
self.__hadoop_version = "2.5.0-zdh2.0.2-hdfs-SNAPSHOT" # str

2. File "pydoop/hdfs/init.py", line 262 
257 def mkdir(hdfs_path, user=None): 
258 """ 
259 Create a directory and its parents as needed. 
260 """ 
261 host=hdfs://defaultCluster/ 
262 port=None 
263 path_ = path.split(hdfs_path, user) 
264 fs = hdfs(host, port, user) 
265 retval = fs.create_directory(path_) 
266 fs.close() 
267 return retval

**Comment by elzaggo** [comment]
Hi.
Could you give more details on the context? Are you, by any chance, running in pydoop source directory?
If it is so, try cd to /tmp and rerun the same script.

--gianluigi

**Comment by ilveroluca** [comment]
We can't reproduce this issue.

**Comment by calloc** [comment]
Hi,

Mine is the problem during building the pydoop library. Here is what happen ....
1) I installed Anaconda on CentOS 6 (python 2.6) to get python 2.7 (using Anaconda parcels with CDH5.8 installed).
2) I exported PATH to the Anaconda /bin directory.
3) I tried "pip install --global-option=build_ext --global-option="-L/path/to/anaconda/lib" pydoop .
4) Then, this error happens.

To fix, I manually edit setup.cfg file to include:

[build_ext]
include_dirs=/path/to/anaconda/include
library_dirs=/path/to/anaconda/lib
rpath=%(library_dirs)s

and clean/build/install --skip_build the sources. Now, the library works again.

I think this would be helpful.
