### ISSUE TITLE
ImportError: No module named pydoop.pipes

### ISSUE THREAD

**Issue by stevenbedrick** [crs4/pydoop#210]
Hello-

I've got a cluster running HDP 2.4, and have installed Pydoop (using Pip) on all  of the nodes. Using `pydoop script`, any job I submit is hanging, and looking at the individual map jobs log files, I'm seeing the following in the stderr:

```
Traceback (most recent call last):
  File "/hadoop/hadoop/yarn/local/usercache/steven/appcache/application_1459139390812_0001/container_e05_1459139390812_0001_01_000014/e27daaf1-00e2-499e-b77b-39fd308a3897", line 9, in <module>
    import pydoop_script_driver_a5e8c8c412774c58b7eae274f975bb8f as module
  File "/hadoop/hadoop/yarn/local/usercache/steven/appcache/application_1459139390812_0001/container_e05_1459139390812_0001_01_000014/pydoop_script_43xHh3/pydoop_script_driver_a5e8c8c412774c58b7eae274f975bb8f.py", line 5, in <module>
    import pydoop.pipes
ImportError: No module named pydoop.pipes
```

To be clear, the Yarn job is being successfully created- I got the error snippet above via the NodeManager web GUI.

Looking at that error, my first thought was that I somehow must have not installed Pydoop correctly on the various nodes trying to run the job. However, I've verified that, on the specific node trying to run the job, it's possible to `import pydoop.pipes` from the Python shell, both as my own user, as root, and also as the user Yarn is running under. So I'm pretty sure that Pydoop is there, but for some reason, Yarn's not being able to find it when it goes to run the MR job.

I'm guessing that it's probably a very stupid mistake on my part, but I'm kind of stuck. Any suggestions or ideas?

**Comment by ilveroluca** [comment]
Hi Steven,

Try running with logging level set to DEBUG. Pydoop should then log the
values of the relevant environment variables. That should give us a hint on
why python isn't finding the module.

Luca
Il 28/mar/2016 06:41, "Steven Bedrick" <notifications@github.com> ha
scritto:

**Comment by stevenbedrick** [comment]
Hi, Luca-

Thanks for the tip. Running it at DEBUG level, I was able to figure out that I was invoking `pydoop script` from within a virtualenv, and so it was passing through all kinds of inappropriate environment variables, which was the root of the issue. Invoking it from the system Python did the trick, sort of- it's running, or rather it's no longer error-ing out.

However, it's not actually processing any of the input. I think I might know why, though- I'm trying to run it on a bzip2 compressed file (containing lines of text). Other bits and pieces of Hadoop infrastructure can read handle bzip2 files natively (they're splittable, Hadoop ships with a BZip2Codec type), but maybe Pydoop does not?

**Comment by elzaggo** [comment]
Hi Steven,
what happens if you impose `org.apache.hadoop.mapreduce.lib.input.TextInputFormat` as inputformat (using the `-inputformat` flag) ? I seem to recall that the default InputFormat used by pydoop is rather unsophisticated.

--gianluigi

**Comment by stevenbedrick** [comment]
Good idea! But that doesn't look like one of the supported options for "pydoop script"- is there some other way I should be running the job?

-SB

**Comment by ilveroluca** [comment]
You can use the -D option to set any property value.

Luca

Il 28/mar/2016 23:51, "Steven Bedrick" <notifications@github.com> ha
scritto:
>
> Good idea! But that doesn't look like one of the supported options for
"pydoop script"- is there some other way I should be running the job?
>
> -SB
>
>
> > On Mar 28, 2016, at 2:05 PM, elzaggo <notifications@github.com> wrote:
> >
> > Hi Steven,
> > what happens if you impose
org.apache.hadoop.mapreduce.lib.input.TextInputFormat as inputformat (using
the -inputformat flag) ? I seem to recall that the default InputFormat used
by pydoop is rather unsophisticated.
> >
> > --gianluigi
> >

**Comment by stevenbedrick** [comment]
OK, I'm feeling *very* stupid here, but what's the property for the InputFormat? I can't find it in mapred-default.xml, and I've always set it programmatically (using the Java API) or using the -inputformat flag (using the Hadoop Streaming API).

Thanks in advance for the help, and for the patience...

-SB

**Comment by ilveroluca** [comment]
Hahahaha no worries!

I don't have a reference handy at the moment, but you should be able to
find it in mapred-default.xml. Search for something like
input.*format.*class

Hope that helps.

**Comment by stevenbedrick** [comment]
Hi, Luca-

Looking at the docs for mapred-default.xml, it doesn't look like there's a parameter to set the input format, which I admit is kind of hard to believe:

https://hadoop.apache.org/docs/current/hadoop-mapreduce-client/hadoop-mapreduce-client-core/mapred-default.xml

Doing some digging in the pydoop source code, it looks like the thing to do is to override the "mapreduce.pipes.inputformat" property, like so:

-D mapreduce.pipes.inputformat=org.apache.hadoop.mapreduce.lib.input.TextInputFormat

That seems to do the trick, though it seems to play heck with the "map input records" counter, which insists on never leaving 0. But that's no biggie...

BTW, Looking at the code, it looks like "pydoop script" does actually have a place where a "-inputformat" argument might go (line 102 of pydoop/script.py), but it doesn't do anything with it. I did some digging to try and figure out what was up with that, but didn't get too far...

Anyway, thanks a bunch for the help!

-SB

**Comment by ilveroluca** [comment]
Hi,

would you mind telling me which input format class is getting used by default?  You should be able to tell from your job's configuration property "mapreduce.job.inputformat.class".

I see that we have a ``--input-format`` argument in ``pydoop submit``, but not in ``pydoop script``; the rationale probably was that in the latter we assume to be working on text data.  Maybe we should re-evaluate that position, since not all text data is created equal :-)

**Comment by ilveroluca** [comment]
Another question:  do the pydoop tests run on your setup?
