### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by cpore** [crs4/pydoop#221]
`  File ".../anaconda3/lib/python3.5/site-packages/pydoop/hdfs/fs.py", line 146, in __init__
    host = common.encode_host(host)
  File ".../anaconda3/lib/python3.5/site-packages/pydoop/hdfs/common.py", line 53, in encode_host
    if isinstance(host, unicode):
NameError: name 'unicode' is not defined
`

**Comment by cpore** [comment]
Using python 3 (anaconda)

I'm guessing this is the issue: http://stackoverflow.com/a/19877309/1647855

**Comment by Chisha14** [comment]
Hello @cpore how to use the code in  "http://stackoverflow.com/a/19877309/1647855".
I installed anaconda3 on ubuntu 64-bit and using PyDev in elipse neon... I didn't know how to use the code in the stackoverflow I am still getting this exception!

**Comment by simleo** [comment]
Python 3 wasn't supported at the time this issue was opened. Although not stable yet, the current `develop` version does support Python 3 (tested only with Apache Hadoop 2.7 on CentOS 7).
