### ISSUE TITLE
Could pydoop HDFS API be used in reducer to access Hadoop HDFS dir and file?

### ISSUE THREAD

**Issue by walterzy** [crs4/pydoop#225]
Hi, Luca:

Can I use pydoop in reducer to access HDFS in Hadoop? I mean if I can use pydoop HDFS API in reducer to make directory, make file or delete dir/file in Hadoop/HDFS?

If so, could you give me a concrete example?

Thanks a lot

Walter

**Comment by ilveroluca** [comment]
Hi Walter,
yes, you can use Pydoop to access HDFS from any Python process -- even your Reducer, if you wrote it in Python (perhaps with Pydoop's MapReduce API).

For examples, have a look at the Pydoop [documentation](http://crs4.github.io/pydoop/), [examples](https://github.com/crs4/pydoop/tree/develop/examples) and [tests](https://github.com/crs4/pydoop/tree/develop/test).

Cheers,

Luca

**Comment by walterzy** [comment]
Thanks Luca.

Unfortunately, I did not find a concrete example of using pydoop HDFS API in reducer which runs via -r hadoop parameter.

Could you please give me a snapshot of the code?

**Comment by wajdii** [comment]
Hye brothers,

Please, Can I use pydoop model in network simulation 3 (ns3) because it accept c++ and python language for coding scripts ? 

If so, could you answer me?

Thanks for helping.
