### ISSUE TITLE
Pip install fails to use at HADOOP_CONF_HOME and errors

### ISSUE THREAD

**Issue by britishbadger** [crs4/pydoop#226]
When pip installing, I get the following error : 

```pydoop.LocalModeNotSupported: ERROR: Hadoop is configured to run in local mode```

My cluster config is stored in a different directory to my hadoop distribution. It seems that setup.py doesn't consider HADOOP_CONF_HOME. during installation.

**Comment by ilveroluca** [comment]
No it doesn't, but it does consider `HADOOP_CONF_DIR`.  I don't see `HADOOP_CONF_HOME` in the Hadoop documentation.

Try setting the `HADOOP_CONF_DIR` environment variable to point to your configuration.

Luca

**Comment by britishbadger** [comment]
Ooops, Problem in Chair Not In Computer ;) I'll try it next time I do a rebuild of our container. 

Thanks

**Comment by ilveroluca** [comment]
:-D

**Comment by ChinaMobileNG** [comment]
Hi, I met the same error when installing pydoop use pip, and my HADOOP_CONF_DIR is set correctly, the installation always failed with pydoop.LocalModeNotSupported

**Comment by frouzbeh** [comment]
@ChinaMobileNG Hi, did you fix the issue? I'm facing the same problem.

**Comment by simleo** [comment]
@frouzbeh are you installing the latest version? Try installing with `pip install --pre`

**Comment by frouzbeh** [comment]
@simleo Thanks, it works now.
