### ISSUE TITLE
pydoop install in cdh5.9 - error - unsupported CDH deployment

### ISSUE THREAD

**Issue by banshidhar83** [crs4/pydoop#227]
Hi,

I am getting below error while installing pydoop. My CDH version is Hadoop 2.6.0-cdh5.9.0.
I don't have internet connectivity from the host.
Please suggest how to fix.

$ anaconda2/bin/pip install pydoop-1.2.0.tar.gz
Processing ./pydoop-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    using setuptools version 27.2.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-noDz8Y-build/setup.py", line 65, in <module>
        import pydoop
      File "pydoop/__init__.py", line 42, in <module>
        _HADOOP_INFO = _PATH_FINDER.find()  # fill the cache ASAP
      File "pydoop/hadoop_utils.py", line 624, in find
        info[a] = getattr(self, a)()
      File "pydoop/hadoop_utils.py", line 599, in hadoop_classpath
        hadoop_home = _cdh_hadoop_home()
      File "pydoop/hadoop_utils.py", line 82, in _cdh_hadoop_home
        raise RuntimeError("unsupported CDH deployment")
    RuntimeError: unsupported CDH deployment
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-noDz8Y-build/

Regards,
Banshi.

**Comment by ilveroluca** [comment]
How did you install CDH?  Pydoop works with "CDH version 4 or 5 installed from dist-specific packages or Cloudera Manager parcels (no tarball)"

**Comment by banshidhar83** [comment]
We installed CDH from Cloudera Manager parcels.

**Comment by banshidhar83** [comment]
Hi ilveroluca,

Any update.

Regards,
Banshi.

**Comment by simleo** [comment]
As of 2.0.0, Pydoop no longer tries to explicitly support the various layouts of customized Hadoop releases such as CDH or HDP. However, if the `hadoop` command is in the `PATH` and `HADOOP_CONF_DIR` points to the correct location, everything *should* work.
