### ISSUE TITLE
Is pydoop required in all nodes of a hadoop cluster?

### ISSUE THREAD

**Issue by banshidhar83** [crs4/pydoop#228]
Hi,

Do we need to install pydoop in all nodes of a hadoop cluster or we should install in only in Client nodes (or app node).

Regards,
Banshi.

**Comment by ilveroluca** [comment]
Hi,

that's one approach and sometimes the simplest one -- especially if you have a file system shared among the compute nodes.  Another approach is [Installation-free usage](http://crs4.github.io/pydoop/self_contained.html).  Either way, the Pydoop package needs to be importable from the nodes that run map and/or reduce tasks.

Luca
