### ISSUE TITLE
support for python3

### ISSUE THREAD

**Issue by arg0** [crs4/pydoop#230]
is there any plan for python3？

**Comment by simleo** [comment]
I'll leave this open so we can close it when the job is done.

**Comment by b-long** [comment]
I see that the last commit on the `develop-py3` branch is about a year old.  Are there particular areas that need support?

**Comment by simleo** [comment]
The current status is https://github.com/simleo/pydoop/commit/41953ad0dde00c2c74ad2f19c5e9f9a823709bc7 (on my fork). It's still pretty unstable, that's why I haven't merged anything to the institutional repo yet. I hope I can do that soon™. After that, any contribution will be greatly appreciated. Sorry for the confusion :)

**Comment by simleo** [comment]
Update: #232 adds Python 3 support. Check the PR description for caveats and notes on future work.

**Comment by simleo** [comment]
Python 3 support now merged to `develop`. Note that we are currently (explicitly) supporting only what's being tested by Travis, i.e., Apache Hadoop 2.7 on CentOS 7.

**Comment by dado0583** [comment]
Which version supports python3? When I pip3 install pydoop it fetches 1.2.0 and fails with a print issue relating to parentheses...

**Comment by simleo** [comment]
Python 3 is supported by the current development version (`develop` branch). We are pretty close to uploading an alpha release to PyPI, then you'll be able to install it with `pip install --pre pydoop`. In the meantime, you can install from the development branch:

```
pip install --upgrade pip
pip install --upgrade -r requirements.txt
git clone -b develop https://github.com/crs4/pydoop.git
cd pydoop
python setup.py build
python setup.py install --skip-build
```

Check out https://github.com/crs4/pydoop/blob/develop/docs/installation.rst for more info.

**Comment by aimiyu** [comment]
run the following command on my Mac os：
> pip install --pre pydoop

but failed with

    error: command 'gcc' failed with exit status 1

**Comment by simleo** [comment]
@aimiyu Mac OS is not explicitly supported (i.e., it "should work on Mac OS", as opposed to "it won't work on Windows"). That being said, what's the full error message? Is that a compilation error or the system complaining there's no compiler at all? In the latter case, the error message should include something like "no developer tools were found at...". If so, install Xcode and retry.

I have just managed to get a successful installation on a freshly reinstalled Mac with the following:

* Install JDK 8 (**not JRE**, the installer should be like `jdk-8u201-macosx-x64.dmg`)
* Install Xcode

Then run:
```
curl -O https://bootstrap.pypa.io/get-pip.py
python get-pip.py --user
export PATH="/Users/${USER}/Library/Python/2.7/bin:${PATH}"
pip install --user virtualenv
virtualenv venv
source venv/bin/activate
curl http://www-eu.apache.org/dist/hadoop/common/hadoop-3.0.3/hadoop-3.0.3.tar.gz | tar xz
export HADOOP_HOME=${PWD}/hadoop-3.0.3
pip install --pre pydoop
```
I hope this helps
