### ISSUE TITLE
Pydoop script: use a templating engine

### ISSUE THREAD

**Issue by simleo** [crs4/pydoop#244]
Minimally `string.template`, but we can consider using something like Jinja.

**Comment by ilveroluca** [comment]
We change the Pydoop script template so rarely that IMHO it isn't worthwhile to add an external dependency like Jinja to simplify the operation.

**Comment by simleo** [comment]
With Jinjia's support for branching the code might be easier to read. But it does change rarely, and `string.template` is faster.

**Comment by simleo** [comment]
Done in #254
