### ISSUE TITLE
Not able to read contents of file when using both read and readline interface

### ISSUE THREAD

**Issue by mkmainali** [crs4/pydoop#280]
I was using this module to read a file written using pickle, i.e. I was trying to unpickle the file. When I pass the file as a part of distributed cache unpickling works but when reading directly from hdfs it was not reading properly. In the case of reading directly from hdfs I was passing the hdfs_file and the unpickle process used both read and readline interface. I was able to trace it the failure in the ways read and readline were implemented. The issue can be reproduced as following

Suppose the content of file is as follows:
```
first line
second line
third line
fourth line
```
Assuming the file is in '/tmp/test.txt', if you execute the following code
```python
import pydoop.hdfs as hdfs

with hdfs.open('/tmp/test.txt') as f:
    print f.read(1)
    print f.readline()
    print f.read(4)
    print f.read(1)
```
Following would be printed
```
f
irst line




```
After the first readline(), further read calls would just print empty spaces. The expected output is,
```
f
irst line

seco
n
```
However, if we do
```python
import pydoop.hdfs as hdfs

with hdfs.open('/tmp/test.txt') as f:
    print f.read(1)
    print f.readline()
    print f.readline()
```
It would print
```
f
irst line

second line

```
For now I was able to fix my issue by modifying the read method to be in consistent with readline. I can work on a PR if this is indeed a bug.

**Comment by simleo** [comment]
Hi. Yes, that's a bug, thanks for reporting it. It should be fixed by #281, a change I was already considering for performance reasons but hadn't implemented yet.
