### ISSUE TITLE
Pydoop install 3.5 print error

### ISSUE THREAD

**Issue by JaBurd** [crs4/pydoop#336]
Attempting to install pydoop in CentOS 7 with python 3.5 and receiving the following error:

```Collecting pydoop
  Using cached https://files.pythonhosted.org/packages/75/75/085a6410b085f231328884ca3349287a8705822ad8afdca715401e5c4f33/pydoop-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i3rrfspq/pydoop/setup.py", line 45
        print 'using setuptools version', setuptools.__version__
                                       ^
    SyntaxError: Missing parentheses in call to 'print'```

**Comment by simleo** [comment]
Hi,

I think you're picking up an old version of Pydoop with no Python 3 support. Since the current version is still marked as alpha, pip does not show it by default. Try running `pip install --pre pydoop`.

**Comment by JaBurd** [comment]
Ahh perfect! I missed that nuance.  Thank you very much for your timely response!
