### ISSUE TITLE
pip3 install error

### ISSUE THREAD

**Issue by vkingnew** [crs4/pydoop#356]
># pip3 install pydoop
>Collecting pydoop
  Downloading https://files.pythonhosted.org/packages/75/75/085a6410b085f231328884ca3349287a8705822ad8afdca715401e5c4f33/pydoop-1.2.0.tar.gz (956kB)
    100% |████████████████████████████████| 962kB 31kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3kmcjv6u/pydoop/setup.py", line 45
        print 'using setuptools version', setuptools.__version__
                                       ^
   > SyntaxError: Missing parentheses in call to 'print'. Did you mean print('using setuptools version', setuptools.__version__)?
    
   > ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3kmcjv6u/pydoop/
You are using pip version 8.1.2, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
running envrioment:

> #cat /etc/centos-release
>CentOS Linux release 7.4.1708 (Core) 
> #python3 -V
>Python 3.6.8
 > #pip3 -V
pip 8.1.2 from /usr/lib/python3.6/site-packages (python 3.6)

**Comment by simleo** [comment]
Hi. Can you please try `pip3 install --pre pydoop`? Hopefully we'll drop the alpha tag soon.

**Comment by simleo** [comment]
> Hi. Can you please try `pip3 install --pre pydoop`? Hopefully we'll drop the alpha tag soon.

Assuming that solves the problem (and Pydoop 2 is now out anyway).
