### ISSUE TITLE
Pydoop Install Error

### ISSUE THREAD

**Issue by orwa-te** [crs4/pydoop#365]
I am trying to install Pydoop on my centos 7 where all requirements are satisfied:
**Hadoop 3.1.1**, **JAVA_HOME**,  **HADOOP_HOME**, jre=1.8.0, python_devel, setup_tools and C++ compiler.
I am getting the following error:

```
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2l9_84lo/pydoop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-58i12i7y-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-2l9_84lo/pydoop/
```

**Comment by simleo** [comment]
Hi. Please post the full build output, i.e., the error above plus what happened before. Make sure you enclose it in [triple backticks](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by orwa-te** [comment]
Thanks, @simleo for your reply.
The problem was because that I was trying this command from the root user which its environment variables path was not configured there.
I could resolve by switching to "Hdadmin" user were requirements are satisfied
