### ISSUE TITLE
the sequence_file example appears to be broken

### ISSUE THREAD

**Issue by elzaggo** [crs4/pydoop#58]
See travis outputs. https://travis-ci.org/elzaggo/pydoop/jobs/44361345

~/build/elzaggo/pydoop/examples/sequence_file ~/build/elzaggo/pydoop/examples
 *** RUNNING sequence_file EXAMPLE(S) ***
INFO:main:running word count
INFO:main:running filter
INFO:main:checking results
375 447
INFO:main:ERROR: number of keys differs

**Comment by simleo** [comment]
Fixed by @mdrio in 319a8ab753ac3e2a1799f3c7f43502a1971de0ff
