### ISSUE TITLE
Unable to get size of path

### ISSUE THREAD

**Issue by MSaifAsif** [crs4/pydoop#85]
I am trying to find the size of a particular directory using the following but I get a module has no attribute error.

```python
>>> import pydoop.hdfs.path as hpath
>>> hpath
<module 'pydoop.hdfs.path' from '/usr/local/lib/python2.7/dist-packages/pydoop/hdfs/path.pyc'>
>>> hpath.abspath('/19026/local_saif/abc.txt')
'hdfs://localhost:54310/19026/local_saif/abc.txt
>>> hpath.dirname('/19026/local_saif/abc.txt)
'/19026/local_saif'
>>> hpath.getsize('/19026/local_saif/abc.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getsize'
```

I am trying to get the size of a directory, i.e I want the size of a particular directory including all subdirectories. Any help in this regard would be appreciated.

**Comment by simleo** [comment]
Hi,

first of all, make sure you're using the latest Pydoop release:

```python
>>> import pydoop
>>> pydoop.__version__
'1.0.0-rc1 [dcb5cba4d2647067010a21bac47b006f3990f3ad]'
```

Second, `getsize` returns `0` for a directory path. If you want to get the size of all files recursively contained in a directory, you can do the following:

```python
>>> import pydoop.hdfs as hdfs
>>> size = sum(_['size'] for _ in hdfs.lsl(dir_path, recursive=True))
```

**Comment by MSaifAsif** [comment]
@simleo Thanks that solved my problem. :+1:
